services:
  web1:
    image: web/project
    restart: always
    container_name: web-projet1
    networks:
      - webservices
      - db
    volumes:
      - data_web1:/var/www/html/


  database1:
    image: mariadb:11.7.2
    container_name: db-projet1
    restart: always
    environment:
       MARIADB_ROOT_PASSWORD: example
    networks:
      - db

  web2:
    image: web/project
    restart: always
    container_name: web-projet2
    networks:
      - webservices2
      - db2
    volumes:
      - data_web2:/var/www/html/

  database2:
    image: mariadb:11.7.2
    container_name: db-projet2
    restart: always
    environment:
       MARIADB_ROOT_PASSWORD: example
    networks:
      - db2
    
  web3:
    image: web/project
    restart: always
    container_name: web-projet3
    networks:
      - webservices3
      - db3
    volumes:
      - data_web3:/var/www/html/


  database3:
    image: mariadb:11.7.2
    container_name: db-projet3
    restart: always
    environment:
       MARIADB_ROOT_PASSWORD: example
    networks:
      - db3


networks:
  webservices:
    name: web-projet1-net
  db:
    name: db-projet1-net
  webservices2:
    name: web-projet2-net
  db2:
    name: db-projet2-net
  webservices3:
    name: web-projet3-net
  db3:
    name: db-projet3-net
volumes:
  data_web1:
    name: data_web1
  data_web2:
    name: data_web2
  data_web3:
    name: data_web3
